services:
  - type: web
    name: ste-chatbot-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    workingDir: backend
    envVars:
      - key: GEMINI_API_KEY
        sync: false
